version: '3'
services:
  url:
     image: screenless-server:latest
     container_name: screenless-server
     restart: always
     volumes:
       - /etc/timezone:/etc/timezone:ro
       - /etc/localtime:/etc/localtime:ro
       - ./data:/app/data
     ports:
       - 2425:5001
