version: '3'
services:
  url:
     image: screenless:latest
     container_name: screenless
     restart: always
     volumes:
       - ./app:/app
     networks:
       - traefik_proxy
     labels:
       - "traefik.enable=true"
       - "traefik.docker.network=traefik_proxy"
       - "traefik.frontend.rule=Host:screenless.romanpeters.nl"
       - "traefik.port=5000"

networks:
  traefik_proxy:
    external: true